export const ALERT = 'ALERT'
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_WARN = 'ALERT_WARN'
export const ALERT_ERROR = 'ALERT_ERROR'
export const VALIDATE_AUTH_TOKEN = 'VALIDATE_AUTH_TOKEN'
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN'


